#Jpa Database config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/magic_map
    username: root
    password: mzy!!!123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  session:
    store-type: redis
  thymeleaf:
    cache: false
  devtools:
    restart:
      exclude: templates/**,static/**
  http:
    multipart:
      enabled: true
      max-request-size: 20MB
      max-file-size: 15MB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: mzy!!!123
    pool:
      max-active: 10
      max-idle: 3
      max-wait: 1
      min-idle: 1
    timeout: 1000
  mvc:
    static-path-pattern: /static/**
server:
  port: 8086
  error:
    whitelabel:
      enabled: false

#qiniu config
qiniu:
  AccessKey: zjviEeakOpDax3FyG3lwWwv7xg9ZEXwBRgS8_9dg
  SecretKey: ShPmMd3WyOYSKvf0SHS4k-vN2XfHzGUFrgGO2FJc
  Bucket: mzy-811
  cdn:
    prefix: p6a8636wy.bkt.clouddn.com

#Spring Security (see detail in WebSecurityConfig.java)
#security:
#  user:
#    name: mzy
#    password: 123
#    role: ADMIN
#logging:
#  level: debug
