#Jpa Database config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/magic_map
    username: root
    password: mzy!!!123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  session:
    store-type: redis
  thymeleaf:
    cache: false
  devtools:
    restart:
      exclude: templates/**,static/**
server:
  port: 8086
  error:
    whitelabel:
      enabled: false
#Spring Security (see detail in WebSecurityConfig.java)
#security:
#  user:
#    name: mzy
#    password: 123
#    role: ADMIN
#logging:
#  level: debug
